"""
check_test_coverage.py
Purpose: Verify that every expected value generated by
         python/generate_test_expected_values_sql.py has a matching test
         reference in sql/tests/*.sql.

Output:  documentation/test_coverage.md
Exit:    non-zero if any key is uncovered (fails CI-style)
"""

import re
import sys
from pathlib import Path

GENERATOR = Path("python/generate_test_expected_values_sql.py")
TESTS_DIR = Path("sql/tests")
OUT = Path("documentation/test_coverage.md")

# ---------------------------------------------------------------------------
# 1. Collect all add("name", ...) calls from the generator
# ---------------------------------------------------------------------------
gen_text = GENERATOR.read_text(encoding="utf-8")
add_pattern = re.compile(r'add\(\s*"([^"]+)"', re.MULTILINE)
expected_keys = sorted(set(add_pattern.findall(gen_text)))

print(f"Expected keys in generator: {len(expected_keys)}")

# ---------------------------------------------------------------------------
# 2. Collect all test_name references from tests/*.sql
# ---------------------------------------------------------------------------
referenced = set()
test_files = sorted(TESTS_DIR.glob("*.sql"))

for tf in test_files:
    text = tf.read_text(encoding="utf-8")
    # Match both `WHERE e.test_name = 'KEY'` and `SELECT 'KEY', ...` patterns
    for m in re.findall(r"test_name\s*=\s*'([^']+)'", text):
        referenced.add(m)
    for m in re.findall(r"SELECT\s+'([a-z][a-z0-9_.]+)'\s*,", text):
        referenced.add(m)

print(f"Referenced test names: {len(referenced)}")

# ---------------------------------------------------------------------------
# 3. Compare
# ---------------------------------------------------------------------------
covered = sorted(set(expected_keys) & referenced)
uncovered = sorted(set(expected_keys) - referenced)
ghosts = sorted(referenced - set(expected_keys))

print(f"\nCovered:   {len(covered)}")
print(f"Uncovered: {len(uncovered)}")
print(f"Ghosts:    {len(ghosts)}")

coverage_pct = 100.0 * len(covered) / len(expected_keys) if expected_keys else 0

# ---------------------------------------------------------------------------
# 4. Write report
# ---------------------------------------------------------------------------
lines = []
lines.append("# Test Coverage — JSON Expected Values to Test Names")
lines.append("")
lines.append(f"**Generated:** {__import__('pandas').Timestamp.now()}")
lines.append(f"**Source:** `python/generate_test_expected_values_sql.py` and `sql/tests/*.sql`")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Summary")
lines.append("")
lines.append(f"| Metric | Count |")
lines.append(f"|--------|------:|")
lines.append(f"| Expected keys in generator | {len(expected_keys)} |")
lines.append(f"| Referenced test names | {len(referenced)} |")
lines.append(f"| Covered | {len(covered)} |")
lines.append(f"| Uncovered | {len(uncovered)} |")
lines.append(f"| Ghosts (referenced, not generated) | {len(ghosts)} |")
lines.append(f"| **Coverage** | **{coverage_pct:.1f}%** |")
lines.append("")

if uncovered:
    lines.append("## Uncovered keys")
    lines.append("")
    lines.append("These keys are generated but have no matching test reference:")
    lines.append("")
    for k in uncovered:
        lines.append(f"- `{k}`")
    lines.append("")

if ghosts:
    lines.append("## Ghost references")
    lines.append("")
    lines.append("These test names are referenced but not generated:")
    lines.append("")
    for k in ghosts:
        lines.append(f"- `{k}`")
    lines.append("")

lines.append("## Full coverage table")
lines.append("")
lines.append("| Expected key | Referenced in tests |")
lines.append("|--------------|:-------------------:|")
for k in expected_keys:
    hit = "yes" if k in referenced else "**NO**"
    lines.append(f"| `{k}` | {hit} |")
lines.append("")

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"\nWrote {OUT}")

# ---------------------------------------------------------------------------
# 5. Exit non-zero if uncovered keys exist
# ---------------------------------------------------------------------------
if uncovered:
    print(f"\n❌ {len(uncovered)} uncovered key(s). Coverage {coverage_pct:.1f}%.")
    sys.exit(1)
else:
    print(f"\n✅ All {len(expected_keys)} expected keys have tests. Coverage 100%.")
    sys.exit(0)