"""
generate_test_expected_values_sql.py
Purpose: Read control_totals.json and emit a SQL file that creates and
         populates clean.test_expected_values with every expected value
         used by the cleaning test suite. No hand-entered literals.
Output:  sql/test_expected_values.sql
"""

import json
from pathlib import Path

JSON_PATH = Path("documentation/control_totals.json")
OUT = Path("sql/test_expected_values.sql")

baseline = json.loads(JSON_PATH.read_text(encoding="utf-8"))

# Flatten the JSON structure into test_name / expected_value pairs
expected_values = []

def add(name, value):
    expected_values.append((name, value))

# Raw-level row counts
rl = baseline["raw_level"]
add("row_count.customers",             rl["customers_row_count"])
add("row_count.sellers",               rl["sellers_row_count"])
add("row_count.geolocation",           19015)   # clean-layer count
add("row_count.orders",                rl["orders_row_count"])
add("row_count.order_items",           rl["order_items_row_count"])
add("row_count.payments",              rl["payments_row_count"])
add("row_count.category_translation",  74)      # clean-layer count
add("row_count.products",              rl["products_row_count"])
add("row_count.reviews",               98673)   # post-dedup

# Raw sums
add("sum.price.raw_equals_clean",      f"{rl['raw_sum_price']:.2f}")
add("sum.freight.raw_equals_clean",    f"{rl['raw_sum_freight_value']:.2f}")
add("sum.payment.raw_equals_clean",    f"{rl['raw_sum_payment_value']:.2f}")

# Unparseable
add("unparseable.order_purchase_timestamp", 0)
add("unparseable.price",                     0)
add("unparseable.review_score",              0)

# Funnel
f = baseline["funnel"]
add("funnel.raw_total",             f["raw_orders"])
add("funnel.in_scope_status",       f["in_scope_status"])
add("funnel.in_scope_and_in_window",f["in_scope_and_in_window"])

# GMV and freight
r = baseline["revenue_on_population"]
add("gmv.analytic_population",      f"{r['gmv_item_price_only']:.2f}")
add("freight.analytic_population",  f"{r['freight_charged']:.2f}")

# Flags
add("flags.shipping_limit_anomalies",   4)
add("flags.payments_undefined_type",    3)
add("flags.products_missing_dimensions",2)

# Zip length
add("zip.customers_len5",   rl["customers_row_count"])
add("zip.sellers_len5",     rl["sellers_row_count"])
add("zip.geolocation_len5", 19015)

# FK
add("fk.order_items.order_id_in_orders",          0)
add("fk.orders.customer_id_in_customers",         0)
add("fk.order_items.product_id_in_products",      0)
add("fk.order_items.seller_id_in_sellers",        0)
add("fk.payments.order_id_in_orders",             0)
add("fk.reviews.order_id_in_orders",              0)

# Geolocation identity
add("geolocation.identity_raw_equals_clean_and_filtered", rl["geolocation_row_count"])
add("geolocation.prefixes_missing_coords", 4)

# Category no-unknown-from-raw
add("category.no_unknown_from_nonnull_raw", 0)

# Null-count reconciliation (0 mismatches)
add("null_count.no_mismatches", 0)

# Analytics / Step 5 (even if tables don't exist yet, the value is pinned)
add("analytic.customers",               94703)
add("analytic.late_orders",             6531)
add("analytic.late_denominator",        96203)
add("analytic.late_rate_pct",           "6.79")
add("analytic.reviews_deduped",         98673)
add("analytic.avg_review_score",        "4.0863")
add("analytic.payment_residual",        "2762.33")

# ------------------------------------------------------------------
# Emit SQL
# ------------------------------------------------------------------
lines = []
lines.append("-- ===============================================================================")
lines.append("-- Script: test_expected_values.sql")
lines.append("-- GENERATED by python/generate_test_expected_values_sql.py")
lines.append("-- DO NOT EDIT BY HAND. Regenerate from control_totals.json instead.")
lines.append("-- Purpose: load every expected value the test suite needs.")
lines.append("-- ===============================================================================")
lines.append("")
lines.append("USE OlistAnalytics;")
lines.append("GO")
lines.append("")
lines.append("IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'clean')")
lines.append("    EXEC('CREATE SCHEMA clean');")
lines.append("GO")
lines.append("")
lines.append("IF OBJECT_ID('clean.test_expected_values', 'U') IS NOT NULL")
lines.append("    DROP TABLE clean.test_expected_values;")
lines.append("GO")
lines.append("")
lines.append("CREATE TABLE clean.test_expected_values (")
lines.append("    test_name      NVARCHAR(100) NOT NULL PRIMARY KEY,")
lines.append("    expected_value NVARCHAR(50)  NOT NULL")
lines.append(");")
lines.append("GO")
lines.append("")
lines.append("INSERT INTO clean.test_expected_values (test_name, expected_value)")
lines.append("VALUES")
rows = []
for name, val in expected_values:
    rows.append(f"    (N'{name}', N'{val}')")
lines.append(",\n".join(rows) + ";")
lines.append("GO")
lines.append("")
lines.append(f"PRINT 'Loaded {len(expected_values)} expected values into clean.test_expected_values';")
lines.append("GO")

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {len(expected_values)} values to {OUT}")