-- ===============================================================================
-- Script: test_expected_values.sql
-- GENERATED by python/generate_test_expected_values_sql.py
-- DO NOT EDIT BY HAND. Regenerate from control_totals.json instead.
-- Purpose: load every expected value the test suite needs.
-- ===============================================================================

USE OlistAnalytics;
GO

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'clean')
    EXEC('CREATE SCHEMA clean');
GO

IF OBJECT_ID('clean.test_expected_values', 'U') IS NOT NULL
    DROP TABLE clean.test_expected_values;
GO

CREATE TABLE clean.test_expected_values (
    test_name      NVARCHAR(100) NOT NULL PRIMARY KEY,
    expected_value NVARCHAR(50)  NOT NULL
);
GO

INSERT INTO clean.test_expected_values (test_name, expected_value)
VALUES
    (N'row_count.customers', N'99441'),
    (N'row_count.sellers', N'3095'),
    (N'row_count.geolocation', N'19015'),
    (N'row_count.orders', N'99441'),
    (N'row_count.order_items', N'112650'),
    (N'row_count.payments', N'103886'),
    (N'row_count.category_translation', N'74'),
    (N'row_count.products', N'32951'),
    (N'row_count.reviews', N'98673'),
    (N'sum.price.raw_equals_clean', N'13591643.70'),
    (N'sum.freight.raw_equals_clean', N'2251909.54'),
    (N'sum.payment.raw_equals_clean', N'16008872.12'),
    (N'unparseable.order_purchase_timestamp', N'0'),
    (N'unparseable.price', N'0'),
    (N'unparseable.review_score', N'0'),
    (N'funnel.raw_total', N'99441'),
    (N'funnel.in_scope_status', N'98202'),
    (N'funnel.in_scope_and_in_window', N'97905'),
    (N'gmv.analytic_population', N'13449529.68'),
    (N'freight.analytic_population', N'2234177.06'),
    (N'flags.shipping_limit_anomalies', N'4'),
    (N'flags.payments_undefined_type', N'3'),
    (N'flags.products_missing_dimensions', N'2'),
    (N'zip.customers_len5', N'99441'),
    (N'zip.sellers_len5', N'3095'),
    (N'zip.geolocation_len5', N'19015'),
    (N'fk.order_items.order_id_in_orders', N'0'),
    (N'fk.orders.customer_id_in_customers', N'0'),
    (N'fk.order_items.product_id_in_products', N'0'),
    (N'fk.order_items.seller_id_in_sellers', N'0'),
    (N'fk.payments.order_id_in_orders', N'0'),
    (N'fk.reviews.order_id_in_orders', N'0'),
    (N'geolocation.identity_raw_equals_clean_and_filtered', N'1000163'),
    (N'geolocation.prefixes_missing_coords', N'4'),
    (N'category.no_unknown_from_nonnull_raw', N'0'),
    (N'null_count.no_mismatches', N'0'),
    (N'analytic.customers', N'94703'),
    (N'analytic.late_orders', N'6531'),
    (N'analytic.late_denominator', N'96203'),
    (N'analytic.late_rate_pct', N'6.79'),
    (N'analytic.reviews_deduped', N'98673'),
    (N'analytic.avg_review_score', N'4.0863'),
    (N'analytic.payment_residual', N'2762.33');
GO

PRINT 'Loaded 43 expected values into clean.test_expected_values';
GO