-- ===============================================================================
-- Script: test_expected_values.sql
-- GENERATED by python/generate_test_expected_values_sql.py
-- DO NOT EDIT BY HAND. Regenerate from control_totals.json instead.
-- ===============================================================================

USE OlistAnalytics;
GO

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'clean')
    EXEC('CREATE SCHEMA clean');
GO

IF OBJECT_ID('clean.test_expected_values', 'U') IS NOT NULL
    DROP TABLE clean.test_expected_values;
GO

CREATE TABLE clean.test_expected_values (
    test_name      NVARCHAR(100) NOT NULL PRIMARY KEY,
    expected_value NVARCHAR(50)  NOT NULL
);
GO

INSERT INTO clean.test_expected_values (test_name, expected_value)
VALUES
    (N'row_count.customers', N'99441'),
    (N'row_count.sellers', N'3095'),
    (N'row_count.geolocation', N'19015'),
    (N'row_count.orders', N'99441'),
    (N'row_count.order_items', N'112650'),
    (N'row_count.payments', N'103886'),
    (N'row_count.category_translation', N'74'),
    (N'row_count.products', N'32951'),
    (N'row_count.reviews', N'98673'),
    (N'sum.price.raw_equals_clean', N'13591643.70'),
    (N'sum.freight.raw_equals_clean', N'2251909.54'),
    (N'sum.payment.raw_equals_clean', N'16008872.12'),
    (N'unparseable.order_purchase_timestamp', N'0'),
    (N'unparseable.price', N'0'),
    (N'unparseable.review_score', N'0'),
    (N'funnel.raw_total', N'99441'),
    (N'funnel.in_scope_status', N'98202'),
    (N'funnel.in_scope_and_in_window', N'97905'),
    (N'gmv.analytic_population', N'13449529.68'),
    (N'freight.analytic_population', N'2234177.06'),
    (N'flags.shipping_limit_anomalies', N'4'),
    (N'flags.payments_undefined_type', N'3'),
    (N'flags.products_missing_dimensions', N'2'),
    (N'zip.customers_len5', N'99441'),
    (N'zip.sellers_len5', N'3095'),
    (N'zip.geolocation_len5', N'19015'),
    (N'fk.order_items.order_id_in_orders', N'0'),
    (N'fk.orders.customer_id_in_customers', N'0'),
    (N'fk.order_items.product_id_in_products', N'0'),
    (N'fk.order_items.seller_id_in_sellers', N'0'),
    (N'fk.payments.order_id_in_orders', N'0'),
    (N'fk.reviews.order_id_in_orders', N'0'),
    (N'geolocation.identity_raw_equals_clean_and_filtered', N'1000163'),
    (N'geolocation.prefixes_missing_coords', N'4'),
    (N'category.no_unknown_from_nonnull_raw', N'0'),
    (N'analytic.fact_orders', N'97905'),
    (N'analytic.excluded_orders', N'1536'),
    (N'analytic.fact_plus_excluded', N'99441'),
    (N'analytic.dim_date', N'1096'),
    (N'analytic.dim_customer', N'94703'),
    (N'analytic.dim_product', N'32578'),
    (N'analytic.dim_seller', N'3029'),
    (N'analytic.late_orders', N'6531'),
    (N'analytic.late_denominator', N'96203'),
    (N'analytic.late_rate_pct', N'6.79'),
    (N'analytic.avg_review_score', N'4.0863'),
    (N'analytic.avg_review_late', N'2.2709'),
    (N'analytic.avg_review_on_time', N'4.2910'),
    (N'analytic.review_late_group', N'6378'),
    (N'analytic.review_on_time_group', N'89182'),
    (N'analytic.payment_residual', N'2762.33'),
    (N'analytic.payment_total', N'15686469.07'),
    (N'analytic.items_total', N'15683706.74'),
    (N'monthly.2017_01.in_scope', N'787'),
    (N'monthly.2017_01.all_statuses', N'800'),
    (N'monthly.2017_02.in_scope', N'1718'),
    (N'monthly.2017_02.all_statuses', N'1780'),
    (N'monthly.2017_03.in_scope', N'2617'),
    (N'monthly.2017_03.all_statuses', N'2682'),
    (N'monthly.2017_04.in_scope', N'2377'),
    (N'monthly.2017_04.all_statuses', N'2404'),
    (N'monthly.2017_05.in_scope', N'3640'),
    (N'monthly.2017_05.all_statuses', N'3700'),
    (N'monthly.2017_06.in_scope', N'3205'),
    (N'monthly.2017_06.all_statuses', N'3245'),
    (N'monthly.2017_07.in_scope', N'3946'),
    (N'monthly.2017_07.all_statuses', N'4026'),
    (N'monthly.2017_08.in_scope', N'4272'),
    (N'monthly.2017_08.all_statuses', N'4331'),
    (N'monthly.2017_09.in_scope', N'4227'),
    (N'monthly.2017_09.all_statuses', N'4285'),
    (N'monthly.2017_10.in_scope', N'4547'),
    (N'monthly.2017_10.all_statuses', N'4631'),
    (N'monthly.2017_11.in_scope', N'7421'),
    (N'monthly.2017_11.all_statuses', N'7544'),
    (N'monthly.2017_12.in_scope', N'5618'),
    (N'monthly.2017_12.all_statuses', N'5673'),
    (N'monthly.2018_01.in_scope', N'7187'),
    (N'monthly.2018_01.all_statuses', N'7269'),
    (N'monthly.2018_02.in_scope', N'6624'),
    (N'monthly.2018_02.all_statuses', N'6728'),
    (N'monthly.2018_03.in_scope', N'7168'),
    (N'monthly.2018_03.all_statuses', N'7211'),
    (N'monthly.2018_04.in_scope', N'6919'),
    (N'monthly.2018_04.all_statuses', N'6939'),
    (N'monthly.2018_05.in_scope', N'6833'),
    (N'monthly.2018_05.all_statuses', N'6873'),
    (N'monthly.2018_06.in_scope', N'6145'),
    (N'monthly.2018_06.all_statuses', N'6167'),
    (N'monthly.2018_07.in_scope', N'6233'),
    (N'monthly.2018_07.all_statuses', N'6292'),
    (N'monthly.2018_08.in_scope', N'6421'),
    (N'monthly.2018_08.all_statuses', N'6512');
GO

PRINT 'Loaded 93 expected values into clean.test_expected_values';
GO